# permissions for end users to view hvaultsecretssyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hvaultsecretssync-viewer-role
rules:
- apiGroups:
  - secretssync.redhat.com
  resources:
  - hvaultsecretssyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secretssync.redhat.com
  resources:
  - hvaultsecretssyncs/status
  verbs:
  - get
