# permissions for end users to edit hvaultsecretssyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hvaultsecretssync-editor-role
rules:
- apiGroups:
  - secretssync.redhat.com
  resources:
  - hvaultsecretssyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secretssync.redhat.com
  resources:
  - hvaultsecretssyncs/status
  verbs:
  - get
