apiVersion: secretssync.redhat.com/v1alpha1
kind: Hvaultsecretssync
metadata:
  name: hvaultsecretssync-sample
  namespace: suman-hvault-02
spec:
  configmap: 'vault-agent-cm'
  serviceaccount: 'default'
