apiVersion: secretssync.redhat.com/v1alpha1
kind: Hvaultsecretssync
metadata:
  name: hvaultsecretssync-sample
  namespace: suman-hvault-01
spec:
  configmap: 'vault-secrets-sync-agent'
  serviceaccount: 'internal-app'
