---
- name: Play to deploy hvault-ocp-sync-secrets
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Start hvault-ocp-sync-secrets
    k8s:
      definition:
        kind: Deployment
        apiVersion: apps/v1
        metadata:
          name: '{{ ansible_operator_meta.name }}-hvault-sync-secrets'
          namespace: '{{ ansible_operator_meta.namespace }}'
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: hvault-sync-secrets
          template:
            metadata:
              labels:
                app: hvault-sync-secrets
            spec:
              serviceAccountName: '{{ serviceaccount }}'
              containers:
                - name: hvault-secrets-sync-agent
                  image: "quay.io/suman.tripuraneni/hvault-ocp-secrets-sync:v0.3"
                  imagePullPolicy: Always
                  env:
                    - name: CONTROLLER_CONFIGMAP_NAME
                      value: '{{ configmap }}'
